### ISSUE TITLE
CUDA Out of Memory Error with Increased Array Size

### ISSUE THREAD

**Issue by ShawnshanksGui** [shacklettbp/gpu_hideseek#6]
I'm testing with the [gpu_hideseek](https://github.com/shacklettbp/gpu_hideseek) project on a machine equipped with a A6000 GPU (50GB of GPU memory).

When I increase the array size of the structure Lidar to 40000 ( maxAgents = 6), I encounter an "out of memory" error:
![image](https://github.com/user-attachments/assets/f8942cdc-c451-4811-a584-0a1e3934b1e4)

```
python scripts/benchmark.py 1 1920 0 0 1
```

```
Error at /data3/gf/projects/test/gpu_hideseek/external/madrona/src/mw/cuda_exec.cpp:1211 in void madrona::gpuVMAllocatorThread(HostChannel *, CUcontext)
CUDA_ERROR_OUT_OF_MEMORY: out of memory
Aborted (core dumped)
Is there a known limitation on the array size for memory allocation that could be causing this issue? Any guidance on how to resolve this would be appreciated.
```

Is there a known limitation on the array size for memory allocation that could be causing this issue? Any guidance on how to resolve this would be appreciated.

**Comment by shacklettbp** [comment]
Can you try on the "update" branch of this repo? main is on quite an old version of Madrona at this point.

**Comment by ShawnshanksGui** [comment]
I have tried it on the "update" branch of this repo, but cannot compile it normally:
```
git clone --recursive git@github.com:shacklettbp/gpu_hideseek.git
cd ./gpu_hideseek/
mkdir build
cd ./build
cmake ..
make -j 60
```
![image](https://github.com/user-attachments/assets/9c3ece4f-9dc1-4242-9b19-0159c509f6cd)

**Comment by shacklettbp** [comment]
Hmm can you do the following:

```
git clone git@github.com:shacklettbp/gpu_hideseek.git
git checkout update
git submodule update --init --recursive # Crucial bit is here, need to update submodules *after* switching branches
mkdir build
cd build
cmake ..
make -j 60
```

**Comment by ShawnshanksGui** [comment]
It works, thx.

**Comment by jedward225** [comment]
since you may update the madrona engine code, this repo can't be launched normally(?
I think some functions of tensor collection may have changed and thus, after following the guidance of the information above, I encountered:

```
(HideAndSeek) jed@JEdward225:~/gpu_hideseek$ python scripts/benchmark.py 1 1920 0 0 1
Compiling GPU engine code:
Error at /home/jed/gpu_hideseek/external/madrona/src/mw/cuda_exec.cpp:1788 in GPUEngineState madrona::initEngineAndUserState(uint32_t, uint32_t, uint32_t, void *, uint32_t, void *, uint32_t, uint32_t, uint32_t, const GPUKernels &, const BVHKernels &, const Optional<CudaBatchRenderConfig> &, ExecutorMode, CUdevice, CUcontext, cudaStream_t)
CUDA_ERROR_INVALID_DEVICE: invalid device ordinal
Aborted (core dumped)
```

```
(HideAndSeek) jed@JEdward225:~/gpu_hideseek$ python scripts/cpu_benchmark.py 2000 1920 0 0 1
Traceback (most recent call last):
  File "/home/jed/gpu_hideseek/scripts/cpu_benchmark.py", line 21, in <module>
    sim = gpu_hideseek.HideAndSeekSimulator(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: __init__(): incompatible function arguments. The following argument types are supported:
    1. __init__(self, exec_mode: gpu_hideseek.madrona.ExecMode, gpu_id: int, num_worlds: int, sim_flags: int, rand_seed: int, min_hiders: int, max_hiders: int, min_seekers: int, max_seekers: int, num_pbt_policies: int, enable_batch_renderer: bool = False, batch_render_width: int = 64, batch_render_height: int = 64) -> None

Invoked with types: gpu_hideseek.HideAndSeekSimulator, kwargs = { exec_mode: gpu_hideseek.madrona.ExecMode, gpu_id: int, num_worlds: int, render_width: int, render_height: int, debug_compile: bool, auto_reset: bool }
(HideAndSeek) jed@JEdward225:~/gpu_hideseek$ q^C

<te HideAndSeek && python scripts/cpu_benchmark.py 2000 1920 0 0 1
Traceback (most recent call last):
  File "/home/jed/gpu_hideseek/scripts/cpu_benchmark.py", line 74, in <module>
    sim.agent_mask_tensor().to_torch(),
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'gpu_hideseek.HideAndSeekSimulator' object has no attribute 'agent_mask_tensor'. Did you mean: 'agent_data_tensor'?
```

btw, I'm using wsl2 ubuntu with my RTX4060 and CUDA 12.8, python version is 3.12.9 ; (

**Comment by jedward225** [comment]
@shacklettbp
